#!/bin/sh

HOUR=$(date -u "+%H")

# AAA is publishing new data at 5 AM AST, I pull at 6 AM AST. 10 UTC
if [ $HOUR != 10 ]; then
    exit
fi
# rest of the script

/usr/bin/env python $OPENSHIFT_REPO_DIR/scrape.py >> $OPENSHIFT_DATA_DIR/niveles.txt
